repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
        args: [--args=-recursive]

      - id: terraform_validate
        args: [--args=-no-color]

      - id: terraform_tflint
        args: ["--args=--enable-rule=terraform_documented_outputs", "--args=--enable-rule=terraform_documented_variables"]

      - id: terraform_trivy
        args: [ "--args=--severity=HIGH,CRITICAL", "--args=--exit-code=1"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ["--baseline", ".secrets.baseline"]
      exclude: |
        (?x)^(
          \.git/|
          \.pre-commit-cache/|
          \.terraform/|
          .*\.tfstate(\..*)?$|
          .*tfplan(\.txt)?$
        )$
